[package]
name = "publisher"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = {version = "^0.8.0"}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.148"
store = {path = "../store"}